defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:title/

include: [.htaccess]