collections:
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
      excerpt_separator: "<!--more-->"
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /tags/:categories/:title/

include: [.htaccess]