defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  -
    scope:
      path: ""
    values:
      layout: "default"

permalink: /:categories/:title/

include: [404.html, .htaccess]