plugins:
  - amp-jekyll

collections:
  tags:
    output: true

defaults:
  - scope:
      path: ""
      type: "tags"
    values:
      layout: "tag"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "blog"
  -
    scope:
      path: ""
    values:
      layout: "default"

ampdir: /amp

permalink: /tags/:categories/:title/

include: [.htaccess]

title: "David Kistauri Blog"
description: "David Kistauri. Frontend developer, web designer, SMM specialist"
url: "dtroode.netlify.com"
author: "David Kistauri"