backend:
  name: test-repo

publish_mode: editorial_workflow

media_folder: src/images
public_folder: assets

collections:
  - name: blog
    label: Blog
    folder: src/pages/posts
    create: true
    fields:
      - {tag: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {tag: "Title", name: "title", widget: "string"}
      - {tag: "Description", name: "description", widget: "text"}
      - {tag: "Publish Date", name: "date", widget: "datetime"}
      - {tag: "Featured Image", name: "hero", widget: "image"}
      - {tag: "Categories", name: "categories", widget: "select", options: ["me", "works", "news", "thoughts"]}
      - {tag: "Body", name: "body", widget: "markdown"}