backend:
  name: master

publish_mode: editorial_workflow

media_folder: "static/img"
public_folder: "img"

collections:
  - name: "blog"
    label: "Blog"
    folder: "src/pages/blog"
    create: true
    slug: "{{slug}}"
    fields:
      - {tag: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {tag: "Title", name: "title", widget: "string"}
      - {tag: "Description", name: "description", widget: "text"}
      - {tag: "Publish Date", name: "date", widget: "datetime"}
      - {tag: "Featured Image", name: "hero", widget: "image"}
      - {tag: "Categories", name: "categories", widget: "select", options: ["me", "works", "news", "thoughts"]}
      - {tag: "Body", name: "body", widget: "markdown"}