backend:
  name: git-gateway
  branch: master

publish_mode: editorial_workflow

media_folder: "/assets/img/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "_posts/"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {tag: "Layout", name: "layout", widget: "hidden", default: "blog"}
      - {tag: "Title", name: "title", widget: "string"}
      - {tag: "Description", name: "description", widget: "text"}
      - {tag: "Publish Date", name: "date", widget: "datetime"}
      - {tag: "Featured Image", name: "thumbnail", widget: "image"}
      - {tag: "Categories", name: "categories", widget: "select", options:
                                                                    - { label: "Me", value: "me" }
                                                                    - { label: "Works", value: "works" }
                                                                    - { label: "News", value: "news" }
                                                                    - { label: "Thoughts", value: "thoughts" }}
      - {tag: "Body", name: "body", widget: "markdown"}